/**
 * IrriCount Quick Quote — PDF generation
 * Two outputs:
 *   generateClientProposalPDF — scope-of-work narrative + sale price only (no COGS)
 *   generateInternalPDF       — full cost breakdown for internal use
 */

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { fmt, buildProposalLine } from './calculations'

// ---------------------------------------------------------------------------
// Colour palette (readable on white paper)
// ---------------------------------------------------------------------------
const C = {
  black:     [15, 23, 42],      // slate-900
  darkBlue:  [30, 41, 59],      // slate-800
  midBlue:   [71, 85, 105],     // slate-500
  lightGray: [241, 245, 249],   // slate-100
  accent:    [14, 116, 144],    // cyan-700
  white:     [255, 255, 255],
}

const PAGE_W = 215.9   // letter width  mm
const PAGE_H = 279.4   // letter height mm
const MARGIN = 14
const COL_W  = PAGE_W - MARGIN * 2

// ---------------------------------------------------------------------------
// Header block — company name bar + job title + rule
// Returns y position after header.
// ---------------------------------------------------------------------------
function headerBlock(doc, settings, inputs, date, subtitle) {
  doc.setFillColor(...C.darkBlue)
  doc.rect(0, 0, PAGE_W, 22, 'F')

  doc.setTextColor(...C.white)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(settings.companyName || 'IrriCount Quick Quote', MARGIN, 14)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated ${date}`, PAGE_W - MARGIN, 14, { align: 'right' })

  doc.setTextColor(...C.black)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(inputs.jobName || 'Quick Quote', MARGIN, 34)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.midBlue)
  doc.text(subtitle, MARGIN, 40)

  doc.setDrawColor(...C.accent)
  doc.setLineWidth(0.8)
  doc.line(MARGIN, 43, PAGE_W - MARGIN, 43)

  return 48
}

// ---------------------------------------------------------------------------
// Footer block
// ---------------------------------------------------------------------------
function footerBlock(doc, settings, date, disclaimer) {
  const footerY = PAGE_H - 18
  doc.setFillColor(...C.lightGray)
  doc.rect(0, footerY - 2, PAGE_W, 22, 'F')

  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.midBlue)

  const contactParts = [settings.companyName, settings.phone, settings.email, settings.address].filter(Boolean)
  if (contactParts.length) {
    doc.text(contactParts.join('  |  '), MARGIN, footerY + 4)
  }
  doc.text(disclaimer, MARGIN, footerY + 9)
  doc.text(`Generated by IrriCount  •  ${date}`, PAGE_W - MARGIN, footerY + 9, { align: 'right' })
}

// ---------------------------------------------------------------------------
// Client Proposal PDF
// Output: scope-of-work narrative + sale price only.
// No labor rates, margins, or COGS are included.
// ---------------------------------------------------------------------------
export function generateClientProposalPDF(inputs, results, settings) {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  let y = headerBlock(doc, settings, inputs, date, 'IRRIGATION SYSTEM PROPOSAL')

  // ── Scope of Work box ──
  const proposalText = buildProposalLine(inputs, results)

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.accent)
  doc.text('SCOPE OF WORK', MARGIN, y + 8)

  const boxTop = y + 11
  doc.setFillColor(...C.lightGray)
  doc.roundedRect(MARGIN, boxTop, COL_W, 32, 2, 2, 'F')

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.black)
  const lines = doc.splitTextToSize(proposalText, COL_W - 8)
  doc.text(lines, MARGIN + 4, boxTop + 10)

  y = boxTop + 32 + 10

  // ── Sale price highlight box ──
  doc.setFillColor(...C.accent)
  doc.roundedRect(MARGIN, y, COL_W, 18, 2, 2, 'F')

  doc.setTextColor(...C.white)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('TOTAL SALE PRICE', MARGIN + 5, y + 11)

  doc.setFontSize(16)
  doc.text(`$${fmt(results.salePrice)}`, PAGE_W - MARGIN - 5, y + 11, { align: 'right' })

  footerBlock(
    doc,
    settings,
    date,
    'This proposal is an estimate based on field inputs. Final pricing subject to site conditions.',
  )

  const safeName = (inputs.jobName || 'quote').replace(/[^a-zA-Z0-9_-]/g, '_')
  doc.save(`irricount_${safeName}_proposal_${Date.now()}.pdf`)
}

// ---------------------------------------------------------------------------
// Internal Estimate PDF
// Output: full cost breakdown for contractor use only.
// ---------------------------------------------------------------------------
export function generateInternalPDF(inputs, results, settings) {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  let y = headerBlock(doc, settings, inputs, date, 'INTERNAL ESTIMATE — NOT FOR CLIENT DISTRIBUTION')

  const { costs, labor } = results
  const taxRate = settings.taxRate ?? 0.0725

  // ── Helper: build table rows ──
  // Columns: Category | Material | Components | Tax | Subtotal
  function makeRow(label, material, components) {
    const tax      = (material + components) * taxRate
    const subtotal = material + components + tax
    return [
      label,
      `$${fmt(material)}`,
      `$${fmt(components)}`,
      `$${fmt(tax)}`,
      `$${fmt(subtotal)}`,
    ]
  }

  const tableRows = [
    makeRow('Pipe & Fittings',    costs.pipe.mainLine + costs.pipe.lateral, costs.pipe.fittings),
    makeRow('Heads & Nozzles',    costs.heads.sprayBodies + costs.heads.rotorHeads, costs.heads.sprayNozzles + costs.heads.flexBarb05 + costs.heads.flexBarb075 + costs.heads.swingPipe),
    makeRow('Valves & Controls',  costs.valves.zoneValves + costs.valves.dripValves, costs.valves.qcv + costs.valves.isolation),
    makeRow('Electrical & Wire',  costs.electrical.wire, costs.electrical.spliceKits + costs.electrical.primerCement),
    makeRow('Accessories',        costs.accessories.rainSensor + costs.accessories.backflow, costs.accessories.smallBoxes + costs.accessories.largeBoxes + costs.accessories.peaGravel),
  ]

  if ((inputs.dripFootage || 0) > 0 || (inputs.dripZones || 0) > 0) {
    tableRows.push(makeRow('Drip System', costs.drip.tube, costs.drip.valves))
  }
  if (((inputs.sleeving2in || 0) + (inputs.sleeving4in || 0)) > 0) {
    tableRows.push(makeRow('Sleeving', costs.sleeving.twoIn + costs.sleeving.fourIn, 0))
  }
  if (costs.misc > 0) {
    tableRows.push(makeRow('Misc', costs.misc, 0))
  }

  // ── Material breakdown table ──
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.accent)
  doc.text('MATERIAL BREAKDOWN', MARGIN, y + 8)

  autoTable(doc, {
    startY: y + 11,
    margin: { left: MARGIN, right: MARGIN },
    head: [['Category', 'Material', 'Components', 'Tax', 'Subtotal']],
    body: tableRows,
    headStyles: {
      fillColor: C.darkBlue,
      textColor: C.white,
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: { fontSize: 8, textColor: C.black },
    alternateRowStyles: { fillColor: C.lightGray },
    columnStyles: {
      0: { cellWidth: 52 },
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right', fontStyle: 'bold' },
    },
  })

  y = doc.lastAutoTable.finalY + 6

  // ── Labor + Pricing summary side-by-side ──
  const halfW = (COL_W - 4) / 2

  // Labor box
  doc.setFillColor(...C.lightGray)
  doc.roundedRect(MARGIN, y, halfW, 40, 2, 2, 'F')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.accent)
  doc.text('LABOR SUMMARY', MARGIN + 3, y + 6)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.black)
  const laborLines = [
    [`${labor.totalHours.toFixed(1)} hrs @ $${fmt(labor.rate)}/hr`, `$${fmt(labor.cost)}`],
  ]
  let ly = y + 13
  for (const [lbl, val] of laborLines) {
    doc.text(lbl, MARGIN + 3, ly)
    doc.text(val, MARGIN + halfW - 3, ly, { align: 'right' })
    ly += 6
  }

  // Pricing box
  const pricingX = MARGIN + halfW + 4
  doc.setFillColor(...C.lightGray)
  doc.roundedRect(pricingX, y, halfW, 40, 2, 2, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.accent)
  doc.text('PRICING SUMMARY', pricingX + 3, y + 6)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.black)
  const pricingLines = [
    ['Material Subtotal', `$${fmt(results.totalMaterial)}`],
    ['Labor', `$${fmt(labor.cost)}`],
    [`Sales Tax (${(Number(taxRate) * 100).toFixed(2)}%)`, `$${fmt(results.salesTax)}`],
    ['Total Direct Cost', `$${fmt(results.totalDirectCost)}`],
  ]
  let py = y + 13
  for (const [lbl, val] of pricingLines) {
    doc.text(lbl, pricingX + 3, py)
    doc.text(val, pricingX + halfW - 3, py, { align: 'right' })
    py += 6
  }

  y += 44

  // ── Sale price ──
  doc.setFillColor(...C.accent)
  doc.roundedRect(MARGIN, y, COL_W, 16, 2, 2, 'F')

  doc.setTextColor(...C.white)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('SALE PRICE', MARGIN + 5, y + 10)
  doc.setFontSize(14)
  doc.text(`$${fmt(results.salePrice)}`, PAGE_W - MARGIN - 5, y + 10, { align: 'right' })

  doc.setFontSize(9)
  doc.setTextColor(...C.midBlue)
  doc.setFont('helvetica', 'normal')
  doc.text(`GM ${Math.round(results.grossMarginPct)}%  ·  ${labor.totalHours.toFixed(1)} labor hrs  ·  ${results.minZones} zone${results.minZones !== 1 ? 's' : ''}`, MARGIN + 5, y + 22)

  footerBlock(
    doc,
    settings,
    date,
    'Internal use only — not for client distribution.',
  )

  const safeName = (inputs.jobName || 'quote').replace(/[^a-zA-Z0-9_-]/g, '_')
  doc.save(`irricount_${safeName}_internal_${Date.now()}.pdf`)
}

// ---------------------------------------------------------------------------
// Materials List PDF
// Output: every line item — description, qty, unit, unit cost, extended cost.
// No labor, no margins, no pricing structure.
// ---------------------------------------------------------------------------
export function generateMaterialsListPDF(inputs, results, settings, _prices) {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  let y = headerBlock(doc, settings, inputs, date, 'MATERIALS LIST — SUPPLIER ORDER COPY')

  const lineItems = results.lineItems || []

  const tableRows = lineItems.map(item => {
    const qty = Number(item.qty || 0)
    const unitCost = Number(item.unitCost || 0)
    const extended = qty * unitCost
    return [
      item.description,
      qty % 1 === 0 ? String(qty) : qty.toFixed(1),
      item.unit,
      `$${fmt(unitCost)}`,
      `$${fmt(extended)}`,
    ]
  })

  // Materials total
  const materialsTotal = lineItems.reduce((sum, item) => {
    return sum + (Number(item.qty || 0) * Number(item.unitCost || 0))
  }, 0)

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.accent)
  doc.text('MATERIAL LINE ITEMS', MARGIN, y + 8)

  autoTable(doc, {
    startY: y + 11,
    margin: { left: MARGIN, right: MARGIN },
    head: [['Description', 'Qty', 'Unit', 'Unit Cost', 'Extended']],
    body: tableRows,
    foot: [['', '', '', 'TOTAL', `$${fmt(materialsTotal)}`]],
    headStyles: {
      fillColor: C.darkBlue,
      textColor: C.white,
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: { fontSize: 8, textColor: C.black },
    footStyles: {
      fillColor: C.darkBlue,
      textColor: C.white,
      fontStyle: 'bold',
      fontSize: 9,
    },
    alternateRowStyles: { fillColor: C.lightGray },
    columnStyles: {
      0: { cellWidth: 76 },
      1: { halign: 'right', cellWidth: 18 },
      2: { halign: 'center', cellWidth: 14 },
      3: { halign: 'right', cellWidth: 28 },
      4: { halign: 'right', fontStyle: 'bold' },
    },
  })

  footerBlock(
    doc,
    settings,
    date,
    'Materials order list only — for internal and supplier use. Does not include labor or pricing.',
  )

  const safeName = (inputs.jobName || 'quote').replace(/[^a-zA-Z0-9_-]/g, '_')
  doc.save(`irricount_${safeName}_materials_${Date.now()}.pdf`)
}
