/**
 * IrriCount Quick Quote — client-facing PDF generation
 * Output: proposal description + sale price only.
 * No labor rates, margins, or COGS are included.
 */

import { jsPDF } from 'jspdf'
import { fmt, buildProposalLine } from './calculations'

// ---------------------------------------------------------------------------
// Colour palette (readable on white paper)
// ---------------------------------------------------------------------------
const C = {
  black:     [15, 23, 42],      // slate-900
  darkBlue:  [30, 41, 59],      // slate-800
  midBlue:   [71, 85, 105],     // slate-500
  lightGray: [241, 245, 249],   // slate-100
  accent:    [14, 116, 144],    // cyan-700
  white:     [255, 255, 255],
}

const PAGE_W = 215.9   // letter width  mm
const PAGE_H = 279.4   // letter height mm
const MARGIN = 14
const COL_W  = PAGE_W - MARGIN * 2

// ---------------------------------------------------------------------------
// Header block — company name bar + job title + rule
// Returns y position after header.
// ---------------------------------------------------------------------------
function headerBlock(doc, settings, inputs, date) {
  doc.setFillColor(...C.darkBlue)
  doc.rect(0, 0, PAGE_W, 22, 'F')

  doc.setTextColor(...C.white)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(settings.companyName || 'IrriCount Quick Quote', MARGIN, 14)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated ${date}`, PAGE_W - MARGIN, 14, { align: 'right' })

  doc.setTextColor(...C.black)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(inputs.jobName || 'Quick Quote', MARGIN, 34)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.midBlue)
  doc.text('IRRIGATION SYSTEM PROPOSAL', MARGIN, 40)

  doc.setDrawColor(...C.accent)
  doc.setLineWidth(0.8)
  doc.line(MARGIN, 43, PAGE_W - MARGIN, 43)

  return 48
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------
export function generatePDF(inputs, results, settings) {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  let y = headerBlock(doc, settings, inputs, date)

  // -------------------------------------------------------------------------
  // Proposal description block
  // -------------------------------------------------------------------------
  const proposalText = buildProposalLine(inputs, results)

  // Label
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.accent)
  doc.text('SCOPE OF WORK', MARGIN, y + 8)

  // Box
  const boxTop = y + 11
  doc.setFillColor(...C.lightGray)
  doc.roundedRect(MARGIN, boxTop, COL_W, 32, 2, 2, 'F')

  // Wrapped proposal text inside box
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.black)
  const lines = doc.splitTextToSize(proposalText, COL_W - 8)
  doc.text(lines, MARGIN + 4, boxTop + 10)

  y = boxTop + 32 + 10

  // -------------------------------------------------------------------------
  // Sale price highlight box
  // -------------------------------------------------------------------------
  doc.setFillColor(...C.accent)
  doc.roundedRect(MARGIN, y, COL_W, 18, 2, 2, 'F')

  doc.setTextColor(...C.white)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('TOTAL SALE PRICE', MARGIN + 5, y + 11)

  doc.setFontSize(16)
  doc.text(`$${fmt(results.salePrice)}`, PAGE_W - MARGIN - 5, y + 11, { align: 'right' })

  // -------------------------------------------------------------------------
  // Footer
  // -------------------------------------------------------------------------
  const footerY = PAGE_H - 18
  doc.setFillColor(...C.lightGray)
  doc.rect(0, footerY - 2, PAGE_W, 22, 'F')

  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.midBlue)

  const contactParts = [settings.companyName, settings.phone, settings.email, settings.address].filter(Boolean)
  if (contactParts.length) {
    doc.text(contactParts.join('  |  '), MARGIN, footerY + 4)
  }
  doc.text(
    'This proposal is an estimate based on field inputs. Final pricing subject to site conditions.',
    MARGIN,
    footerY + 9,
  )
  doc.text(`Generated by IrriCount  •  ${date}`, PAGE_W - MARGIN, footerY + 9, { align: 'right' })

  // -------------------------------------------------------------------------
  // Save
  // -------------------------------------------------------------------------
  const safeName = (inputs.jobName || 'quote').replace(/[^a-zA-Z0-9_-]/g, '_')
  doc.save(`irricount_${safeName}_${Date.now()}.pdf`)
}
